spring:
  profiles:
    group:
      "local": "local,common"
      "production": "production,common"

---
spring:
  config:
    activate:
      on-profile: common

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:classpath:/application-local.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/ebbinghaus
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://${USERNAME}:${PASSWORD}@${DB_NAME}-mysql.services.clever-cloud.com:3306/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate